#!/usr/bin/env python3
"""Turn IRIS's REX3 draw-shape corpus into a C header for tb_rex3draw.

WHY THIS EXISTS. `iris/src/rex3_shaders.rs` is generated from a profile file
collected by running a real IRIX desktop under IRIS: one entry per distinct
(DRAWMODE0, DRAWMODE1, CLIPMODE) triple the emulated REX3 was actually asked
for. That is a far better list of what the rasteriser has to get right than
anything anyone would think to write down - it is what Xsgi, the toolkit, the
window manager and the GL library between them really use.

    python3 tools/rex3_corpus.py --iris ../iris -o verilator/rex3_corpus.h

The host shapes are dropped: READ, COLORHOST and ALPHAHOST carry state across
GOs that tb_rex3draw does not model, and they have their own tests
(tests/run-rex3.sh, verilator/tb_mcdma.cpp, tests/run-dma.sh).
"""
import argparse
import os
import re
import sys

DEFAULT_IRIS = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                            "..", "..", "iris")

LINE = re.compile(r"/// dm0=0x([0-9a-fA-F]+) dm1=0x([0-9a-fA-F]+) cm=0x([0-9a-fA-F]+)")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--iris", default=DEFAULT_IRIS,
                    help="path to the iris checkout (default: ../iris)")
    ap.add_argument("-o", "--out", required=True)
    args = ap.parse_args()

    src = os.path.join(args.iris, "src", "rex3_shaders.rs")
    if not os.path.exists(src):
        sys.exit("no %s - point --iris at the iris checkout" % src)

    rows, dropped = [], 0
    with open(src, encoding="utf-8", errors="replace") as fh:
        for line in fh:
            m = LINE.match(line)
            if not m:
                continue
            dm0, dm1, cm = (int(g, 16) for g in m.groups())
            opcode = dm0 & 3
            colorhost = (dm0 >> 6) & 1
            alphahost = (dm0 >> 7) & 1
            if opcode == 1 or colorhost or alphahost:      # READ / host source
                dropped += 1
                continue
            rows.append((dm0, dm1, cm))

    with open(args.out, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("// @generated by tools/rex3_corpus.py - do not edit.\n")
        fh.write("// Source: %s\n" % os.path.normpath(src).replace("\\", "/"))
        fh.write("//\n")
        fh.write("// Every non-host (DRAWMODE0, DRAWMODE1, CLIPMODE) triple in IRIS's\n")
        fh.write("// draw-shape corpus: what a real IRIX desktop asked REX3 for.\n")
        fh.write("// %d shapes kept, %d host shapes dropped.\n\n" % (len(rows), dropped))
        fh.write("static const uint32_t REX3_CORPUS[][3] = {\n")
        for dm0, dm1, cm in rows:
            fh.write("    { 0x%08x, 0x%08x, 0x%08x },\n" % (dm0, dm1, cm))
        fh.write("};\n")
        fh.write("static const size_t REX3_CORPUS_N =\n"
                 "    sizeof(REX3_CORPUS) / sizeof(REX3_CORPUS[0]);\n")

    print("%s: %d shapes (%d host shapes dropped)" % (args.out, len(rows), dropped))


main()
